package(
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "sourcepos",
    srcs = ["sourcepos.c"],
    hdrs = [
        "input.h",
        "sourcepos.h",
    ],
    defines = ["_GNU_SOURCE"],
)
