# -*- mode: python -*-
Import('env')

sources = ['sourcepos.c']

env.Library('sourcepos', sources)

env.Tar(env['TARBALL'],
        sources + ['SConscript',
                   'input.h',
                   'sourcepos.h'])

SConscript(['filtergen/SConscript',
            'iptables-save/SConscript'], 'env')
