#define TOK_ACCEPT 2
#define TOK_DEST 3
#define TOK_DPORT 4
#define TOK_DROP 5
#define TOK_FORWARD 6
#define TOK_ICMPTYPE 7
#define TOK_INCLUDE 8
#define TOK_INPUT 9
#define TOK_LCURLY 20
#define TOK_LOCAL 10
#define TOK_LOG 11
#define TOK_LSQUARE 23
#define TOK_MASQ 12
#define TOK_OUTPUT 13
#define TOK_PROTO 14
#define TOK_PROXY 15
#define TOK_RCURLY 21
#define TOK_REDIRECT 16
#define TOK_REJECT 25
#define TOK_RSQUARE 24
#define TOK_SEMICOLON 22
#define TOK_SOURCE 17
#define TOK_SPORT 18
#define TOK_STRINGLITERAL 1
#define TOK_TEXT 19
