#define TOK_ACCEPT 1
#define TOK_DEST 2
#define TOK_DPORT 3
#define TOK_DROP 4
#define TOK_FORWARD 5
#define TOK_ICMPTYPE 6
#define TOK_INCLUDE 7
#define TOK_INPUT 8
#define TOK_LCURLY 9
#define TOK_LOCAL 10
#define TOK_LOG 11
#define TOK_LSQUARE 12
#define TOK_MASQ 13
#define TOK_OUTPUT 14
#define TOK_PROTO 15
#define TOK_PROXY 16
#define TOK_RCURLY 17
#define TOK_REDIRECT 18
#define TOK_REJECT 19
#define TOK_RSQUARE 20
#define TOK_SEMICOLON 21
#define TOK_SOURCE 22
#define TOK_SPORT 23
#define TOK_STRINGLITERAL 24
#define TOK_TEXT 25

#define TOK_IDENTIFIER 27
#define TOK_NUMBER 28
#define TOK_DOT 29
#define TOK_SLASH 30
#define TOK_ERR 31
