cc_library(
    name = "out_ipchains",
    srcs = ["fg-ipchains.c"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:filter",
        "//:gen",
        "//:oputs",
        "//:util",
        "//:flags",
    ],
)
