# -*- mode: python -*-
Import('env')

env.Library('out_ipchains',
            source=['fg-ipchains.c'],
            CPPPATH='../..')

env.Tar(env['TARNAME'], ['SConscript',
                                 'fg-ipchains.c', ])
