# -*- mode: python -*-
Import('env')

sources = ['parser.y',
           'scanner.l',
           'include.c',
           'resolver.c',
           'glue.c']

env.Library('in_filtergen', sources)
env.Clean('scanner.o', ['scanner.c', 'scanner.h'])
env.Clean('parser.o', ['parser.c', 'parser.h'])

env.Tar(env['TARBALL'], sources + ['SConscript',
                                   'ast.h',
                                   'resolver.h',
                                   'include.h',
                                   # build these so users don't have to
                                   # require flex and bison
                                   'parser.c', 'parser.h', 'scanner.c', ])

SConscript('t/SConscript', 'env')
