Import('env')

sources=['parser.yy',
	 'scanner.ll',
	 'driver.cc',
	 'glue.cc',
	 ]
env.Library('in_iptables_save', sources)

# ship the sources
env.Distribute(env['DISTTREE'], sources + ['SConscript',
					   'ast.h',
					   # these included so bison and flex aren't
					   # required by users
					   'parser.cc',
					   'parser.hh',
					   'scanner.cc'
					   ])

SConscript('t/SConscript', 'env')
