# -*- mode: python -*-
Import('env')

env.Library('out_filtergen',
            source=['emit.c'],
            CPPPATH='../..')

env.Tar(env['TARNAME'], ['SConscript',
                         'emit.c', ])
