package(
    default_visibility = ["//:__subpackages__"],
)

filegroup(
    name = "filtergen-dg",
    srcs = ["filtergen-dg.exp"],
)

filegroup(
    name = "fg-scan-dg",
    srcs = ["fg-scan-dg.exp"],
)
