package(
    default_visibility = ["//:__subpackages__"],
)

filegroup(
    name = "filtergen-dg",
    srcs = ["filtergen-dg.exp"],
)

filegroup(
    name = "fg-scan-dg",
    srcs = ["fg-scan-dg.exp"],
)

filegroup(
    name = "fg-parse-dg",
    srcs = ["fg-parse-dg.exp"],
)

filegroup(
    name = "fg-emit-dg",
    srcs = [
        "compare.exp",
        "fg-emit-dg.exp",
    ],
)

filegroup(
    name = "fg-convert-dg",
    srcs = [
        "compare.exp",
        "fg-convert-dg.exp",
    ],
)

filegroup(
    name = "ipts-scan-dg",
    srcs = ["ipts-scan-dg.exp"],
)

filegroup(
    name = "ipts-parse-dg",
    srcs = ["ipts-parse-dg.exp"],
)
