# -*- mode: python -*-
Import('env')

env.Tar(env['TARNAME'], ['SConscript',
                                 'flow',
                                 'generator.notes',
                                 'notes', ])
