# -*- mode: python -*-
Import('env')

env.Distribute(env['DISTTREE'], ['SConscript',
                                 'flow',
                                 'generator.notes',
                                 'notes', ])
