# -*- mode: python -*-
Import('env')

sources = ['ir.c', ]

env.Tar(env['TARNAME'], sources + ['SConscript',
                                           'ir.h',
                                           'emit.c'])

t = env.Clone()

iremit = t.Program('iremit', source=sources + ['emit.c'])
t.Default(iremit)
