# -*- python -*-
Import('env')

sources = ['ir.c',
	   ]

env.Library('ir', sources)

env.Distribute(env['DISTTREE'], sources + ['SConscript',
					   'ir.h',
					   'emit.c'
					   ])

t = env.Copy()

t.AppendUnique(CPPPATH=['../../..', '..'],
			   LIBPATH=['.'],
			   LIBS=['ir'],
			   )
iremit = t.Program('iremit', source=['emit.c'])
