cc_library(
    name = "out_iptablesrestore",
    srcs = ["fg-iptablesrestore.c"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:filter",
        "//:gen",
        "//:oputs",
        "//:util",
    ],
)
