# -*- mode: python -*-
Import('env')

env.Library('out_ipfilter',
            source=['fg-ipfilter.c'],
            CPPPATH='../..')

env.Tar(env['TARNAME'], ['SConscript',
                         'fg-ipfilter.c'])
