cc_library(
    name = "out_iptables",
    srcs = ["fg-iptables.c"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:filter",
        "//:gen",
        "//:oputs",
        "//:util",
        "//:flags",
    ],
)
