# -*- mode: python -*-
Import('env')

env.Tar(env['TARBALL'], ['SConscript', 'config',
                         'lib', 'filtergen'] + env.Glob('*.dg'))

f = env.DejaGnu('filtergen')
env.Depends(f, '#filtergen')
fgp = env.DejaGnu('fg-parse')
env.Depends(fgp, '#input/filtergen/t/parse')
fgs = env.DejaGnu('fg-scan')
env.Depends(fgs, '#input/filtergen/t/scan')
iptsp = env.DejaGnu('ipts-parse')
env.Depends(iptsp, '#input/iptables-save/t/parse')
iptss = env.DejaGnu('ipts-scan')
env.Depends(iptss, '#input/iptables-save/t/scan')

suites = [f, fgp, fgs, iptsp, iptss]

env.Depends(suites, '#site.exp')
env.Depends(suites, env.Glob('config/*.exp'))
# This one's too broad; one lib per suite.
env.Depends(suites, env.Glob('lib/*.exp'))

env.Alias('check', suites)
