# -*- mode: python -*-
Import('env')

env = env.Clone()
env.Append(CPPPATH='..')

env.Program(
    'convert',
    ['convert.c', '../scanner.o', '../parser.o', '../glue.o', '../filter.o',
     '../fg-util.o'])
env.Program('factorise', ['factorise.c', '../scanner.o', '../parser.o'])
