#!/bin/sh

TEST="that the scanner works"

here=`pwd`
if test $? -ne 0 ; then exit 2 ; fi

work=${TMP_DIR-/tmp}/filtergen-test-$$

pass () {
    cd $here
    rm -rf $work
    exit 0
}

fail () {
    cd $here
    rm -rf $work
    echo "FAILED testing $TEST"
    exit 1
}

no_result () {
    cd $here
    rm -rf $work
    echo "NO RESULT when testing $TEST"
    exit 2
}

trap no_result 1 2 3 15

# check for the source dir
if test -f ../filtergen.c ; then
    testdir=.
elif test -f filtergen.c ; then
    testdir=t
fi

# srcdir gets defined by the automake test caller, assume it's not defined
# by the user's environment, so set debug trace on when run manually
test "x$srcdir" = "x" && set -x

mkdir $work
if test $? -ne 0 ; then no_result ; fi

$testdir/scan < $testdir/data/scanner1.in > $work/out
if test $? -ne 0 ; then no_result ; fi

cmp $testdir/data/scanner1.out $work/out
if test $? -ne 0 ; then fail ; fi

# got this far?
pass

