#!/bin/sh

TEST="that filtergen punctuation scanned correctly"

# source the usual stuff
. ./testlib

$testdir/scan < $testdir/data/scanner5.in > $work/out
if test $? -ne 0 ; then no_result ; fi

cmp $testdir/data/scanner5.out $work/out
if test $? -ne 0 ; then fail ; fi

# got this far?
pass

