#!/bin/sh

TEST="that filtergen punctuation scanned correctly"

testdir=`dirname $0`
. $testdir/testlib

./scan < $testdir/data/scanner5.in > $work/out
if test $? -ne 0 ; then no_result ; fi

cmp $testdir/data/scanner5.out $work/out
if test $? -ne 0 ; then
    diff -u $testdir/data/scanner5.out $work/out
    fail
fi

# got this far?
pass

