#!/bin/sh

TEST="that non-keyword identifiers are scanned correctly"

# source the usual stuff
. ./testlib

$testdir/scan < $testdir/data/scanner7.in > $work/out
if test $? -ne 0 ; then no_result ; fi

cmp $testdir/data/scanner7.out $work/out
if test $? -ne 0 ; then fail ; fi

# got this far?
pass

