#!/bin/sh

TEST="that bad comments are scanned and flag errors"

# source the usual stuff
. ./testlib

$testdir/scan < $testdir/data/scanner9.in > $work/out
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/scanner9.out $work/out

# got this far?
pass

