#!/bin/sh

TEST="that c style comments with nested /* are scanned correctly"

# source the usual stuff
. ./testlib

$testdir/scan < $testdir/data/scanner10.in > $work/out
if test $? -ne 0 ; then no_result ; fi

cmp $testdir/data/scanner10.out $work/out
if test $? -ne 0 ; then fail ; fi

# got this far?
pass

