#!/bin/sh

TEST="that c style comments are scanned and ignored"

# source the usual stuff
. ./testlib

$testdir/scan < $testdir/data/scanner11.in > $work/out
if test $? -ne 0 ; then no_result ; fi

cmp $testdir/data/scanner11.out $work/out
if test $? -ne 0 ; then
    diff -u $testdir/data/scanner11.out $work/out
    fail
fi

# got this far?
pass

