#!/bin/sh

TEST="that c style comments are scanned and ignored"

testdir=`dirname $0`
. $testdir/testlib

./scan < $testdir/data/scanner12.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/scanner12.out $work/out

# got this far?
pass

