#!/bin/sh

TEST="that including more than one file works"

# source the usual stuff
. ./testlib

$testdir/scan < $testdir/data/scanner13.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/scanner13.out $work/out

# got this far?
pass

