#!/bin/sh

TEST="that parsing the empty program works"

testdir=`dirname $0`
. $testdir/testlib

./parse < $testdir/data/parser1.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/parser1.out $work/out

# got this far?
pass

