#!/bin/sh

TEST="that parsing a list of empty rules works"
DATA=parser3

testdir=`dirname $0`
. $testdir/testlib

./parse < $testdir/data/${DATA}.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/${DATA}.out $work/out

# got this far?
pass

