#!/bin/sh

TEST="that chained subgroups are parsed correctly"
DATA=parser14

testdir=`dirname $0`
. $testdir/testlib

./parse < $testdir/data/${DATA}.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/${DATA}.out $work/out

./parse < $work/out > $work/out.out

compare $work/out $work/out.out

# got this far?
pass

