#!/bin/sh

TEST="that the examples from the filter_syntax(7) page work"
DATA=example1

testdir=`dirname $0`
. $testdir/testlib

./parse < $testdir/data/${DATA}.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/${DATA}.out $work/out

# got this far?
pass

