#!/bin/sh

TEST="that the parser can cope with included files"
DATA=parser16

testdir=`dirname $0`
. $testdir/testlib

cd $work
if test $? -ne 0 ; then no_result ; fi

cat > include.conf <<EOF
http
ssh
EOF
if test $? -ne 0 ; then no_result ; fi

$here/parse < $testdir/data/${DATA}.in > $work/out 2>&1
if test $? -ne 0 ; then no_result ; fi

compare $testdir/data/${DATA}.out $work/out

# got this far?
pass

