#!/bin/sh

TEST="that directory inclusion works with files"

testdir=`dirname $0`
. $testdir/testlib

cat >$work/in <<EOF
include $work/include.d
EOF
if test $? -ne 0 ; then no_result; fi

mkdir $work/include.d
if test $? -ne 0 ; then no_result; fi

cat > $work/include.d/foo <<EOF
dport pants
EOF
if test $? -ne 0 ; then no_result; fi

mkdir $work/include.d/foo.d
if test $? -ne 0 ; then no_result; fi

cat > $work/include.d/foo.d/bar <<EOF
dest unknown
EOF
if test $? -ne 0 ; then no_result; fi

$testdir/scan < $work/in > $work/out 2>&1
if test $? -ne 0 ; then fail ; fi

test "x$srcdir" = "x" && cat $work/out

cat >$work/good <<EOF
EOF

compare $work/good $work/out

# got this far?
pass
