#!/bin/sh

TEST="that empty rules get parsed correctly"

testdir=`dirname $0`
. $testdir/testlib

cat > $work/rules <<EOF
input eth0 {
    proto tcp dport ssh accept;
    /* empty */;
};
EOF
if test $? -ne 0 ; then no_result ; fi

$here/convert < $work/rules > $work/out
if test $? -ne 0 ; then fail ; fi

cat > $work/good <<EOF
( siblist
  ( input eth0
   )
  child
  ( siblist
    ( siblist
      ( proto tcp
       )
      child
      ( siblist
        ( dport ssh
         )
        child
        ( accept
         )
       )
     )
   )
 )
EOF

compare $work/good $work/out

# got this far?
pass
