#!/bin/sh -x

TEST="that include paths don't start at root"

testdir=`dirname $0`
. $testdir/testlib

cat >$work/in <<EOF
include /
EOF
if test $? -ne 0 ; then no_result; fi

$here/scan < $work/in > $work/out 2>&1
if test $? -ne 0 ; then fail ; fi

test "x$srcdir" = "x" && cat $work/out

cat >$work/good <<EOF
(standard input):1: warning: cannot include / path; skipping
EOF

compare $work/good $work/out

# got this far?
pass
