# -*- mode: python -*-
Import('env')

env.Distribute(env['DISTTREE'], ['SConscript',
                                 'scan.c',
                                 'parse.c',
                                 'emit.c', ])

env = env.Clone()
env.AppendUnique(LIBS=['in_filtergen', 'sourcepos'])

env.Alias('test-binaries', [env.Program('scan.c'),
                            env.Program('parse.c'),
                            env.Program('emit.c'),
                            # env.Program('convert', source=['#t/convert.c', '#filter.o',
                            # '#fg-util.o'])
                            ])
