# -*- mode: python -*-
Import('env')

env.Tar(env['TARNAME'], ['SConscript',
                         'scan.c',
                         'parse.c',
                         'emit.c', ])

env = env.Clone()
env.AppendUnique(LIBS=['in_filtergen', 'sourcepos'])

env.Alias('test-binaries', [env.Program('scan.c'),
                            env.Program('parse.c'),
                            env.Program('emit.c'),
                            ])
