# -*- mode: python -*-
Import('env')

env.Library('out_cisco',
            source=['fg-cisco.c'],
            CPPPATH='../..')

env.Tar(env['TARBALL'], ['SConscript',
                         'fg-cisco.c', ])
